# Generated by Django 4.2.7 on 2023-12-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
                ('email', models.EmailField(default='user@example.com', max_length=254, unique=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
    ]
