# Generated by Django 4.2.7 on 2023-12-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_usuarios_usuario_alter_usuario_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='user',
            new_name='username',
        ),
    ]
