# Generated by Django 4.2.7 on 2023-12-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_user_usuario_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='user',
        ),
    ]
