# Generated by Django 4.2.7 on 2023-12-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_username_usuario_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
    ]
