# Generated by Django 4.2.7 on 2023-12-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_usuario_managers_usuario_date_joined_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
