# Generated by Django 4.2.7 on 2023-11-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCotizar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.TextField(verbose_name='nombre')),
                ('telefono', models.TextField(verbose_name='telefono')),
                ('email', models.TextField(verbose_name='email')),
                ('nombre_empresa', models.TextField(verbose_name='nombre_empresa')),
                ('mensaje', models.TextField(verbose_name='mensaje')),
            ],
            options={
                'db_table': 'cotizacion',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Cotizar',
        ),
    ]
