# Generated by Django 4.2.7 on 2023-11-26 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0002_formcotizar_delete_cotizar'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formcotizar',
            table='cotizar',
        ),
    ]
