# Generated by Django 4.2.7 on 2023-11-26 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0003_alter_formcotizar_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='formcotizar',
            table='cotizacion',
        ),
    ]
