# Generated by Django 4.2.7 on 2023-11-28 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0004_alter_formcotizar_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formcotizar',
            options={'managed': True},
        ),
    ]
