# Generated by Django 4.2.7 on 2024-02-08 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_productos', '__first__'),
        ('cotiza_gral', '0005_alter_cotizacion_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='id_prodcuto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='control_productos.producto', verbose_name='producto'),
        ),
    ]
