# Generated by Django 4.2.7 on 2023-11-28 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0006_alter_formcotizar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formcotizar',
            options={'managed': True},
        ),
    ]
