# Generated by Django 4.2.7 on 2024-02-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0006_cotizacion_id_prodcuto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='id_prodcuto',
            new_name='id_producto',
        ),
    ]
