# Generated by Django 4.2.7 on 2024-02-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0007_rename_id_prodcuto_cotizacion_id_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='id_producto',
        ),
    ]
