# Generated by Django 4.2.7 on 2023-11-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0007_alter_formcotizar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formcotizar',
            options={},
        ),
        migrations.AlterField(
            model_name='formcotizar',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='formcotizar',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='formcotizar',
            name='nombre_cliente',
            field=models.CharField(max_length=255, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='formcotizar',
            name='nombre_empresa',
            field=models.CharField(max_length=255, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='formcotizar',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterModelTable(
            name='formcotizar',
            table=None,
        ),
    ]
