# Generated by Django 4.2.7 on 2023-11-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0008_alter_formcotizar_options_alter_formcotizar_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcotizar',
            name='nombre_cliente',
            field=models.CharField(max_length=25, verbose_name='Nombre del Cliente'),
        ),
    ]
