# Generated by Django 4.2.7 on 2023-11-28 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0009_alter_formcotizar_nombre_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formcotizar',
            options={'managed': False},
        ),
    ]
