# Generated by Django 4.2.7 on 2023-11-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0011_alter_formcotizar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcotizar',
            name='telefono',
            field=models.CharField(max_length=200, verbose_name='Teléfono'),
        ),
        migrations.AlterModelTable(
            name='formcotizar',
            table='cotizacion',
        ),
    ]
