# Generated by Django 4.2.7 on 2023-11-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0012_alter_formcotizar_telefono_alter_formcotizar_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormCotizar',
        ),
    ]
