# Generated by Django 4.2.7 on 2023-11-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotiza_gral', '0013_delete_formcotizar'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCotizar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=25, verbose_name='Nombre del Cliente')),
                ('telefono', models.CharField(max_length=200, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('nombre_empresa', models.CharField(max_length=255, verbose_name='Nombre de la Empresa')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'db_table': 'cotizacion',
                'managed': True,
            },
        ),
    ]
