# Generated by Django 4.2.7 on 2023-11-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0014_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormCotizar',
        ),
    ]
