# Generated by Django 4.2.7 on 2023-11-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0017_formcotizar_delete_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=360, null=True)),
                ('estatus', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cotizacion',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='FormCotizar',
        ),
    ]
