# Generated by Django 4.2.7 on 2023-11-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0018_cotizacion_delete_formcotizar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cotizacion',
        ),
    ]
