# Generated by Django 4.2.7 on 2023-11-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0020_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='telefono',
            new_name='tele',
        ),
    ]
