# Generated by Django 4.2.7 on 2023-11-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0021_rename_telefono_cotizacion_tele'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='tele',
            new_name='telefono',
        ),
    ]
