# Generated by Django 4.2.7 on 2023-11-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0022_rename_tele_cotizacion_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='nombre_cliente',
            field=models.CharField(max_length=100, verbose_name='cliente'),
        ),
    ]
