# Generated by Django 4.2.7 on 2023-11-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0023_alter_cotizacion_nombre_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='mensaje',
            field=models.CharField(blank=True, max_length=360, null=True, verbose_name='mensaje'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='nombre_cliente',
            field=models.CharField(max_length=100, verbose_name='nombre_cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nombre_empresa'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='telefono'),
        ),
    ]
