# Generated by Django 4.2.7 on 2023-12-02 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0024_alter_cotizacion_email_alter_cotizacion_mensaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='fecha',
        ),
    ]
