# Generated by Django 4.2.7 on 2023-12-02 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0025_remove_cotizacion_estatus_remove_cotizacion_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={},
        ),
    ]
