# Generated by Django 4.2.7 on 2023-12-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0026_alter_cotizacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='estatus',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='status'),
        ),
    ]
