# Generated by Django 4.2.7 on 2023-12-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0027_alter_cotizacion_options_cotizacion_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha'),
        ),
    ]
