# Generated by Django 4.2.7 on 2023-12-05 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cotiza_gral', '0029_alter_cotizacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
