# Generated by Django 4.2.7 on 2023-12-21 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_subcategorias', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'managed': False},
        ),
    ]
