# Generated by Django 4.2.7 on 2023-12-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_subcategorias', '0004_alter_categoria_options_alter_subcategoria_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='id_categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Subcategoria',
        ),
    ]
