# Generated by Django 4.2.7 on 2023-12-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_subcategorias', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='nombre_categoria',
        ),
        migrations.RenameField(
            model_name='subcategoria',
            old_name='nombre',
            new_name='nombre_subcategoria',
        ),
    ]
