# Generated by Django 4.2.7 on 2023-12-22 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_subcategorias', '0007_rename_nombre_categoria_nombre_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={},
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_subcategorias.categoria'),
        ),
        migrations.AlterModelTable(
            name='categoria',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subcategoria',
            table=None,
        ),
    ]
