# Generated by Django 4.2.7 on 2023-12-22 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_subcategorias', '0008_alter_categoria_options_alter_subcategoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='subcategoria',
            table='subcategoria',
        ),
    ]
